## GHG Emissions in Canada

In [1]:
#LOAD THE RAW DATA

import pandas as pd

df = pd.read_csv("GHG Provinces & Territories Raw Data.csv")


df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17914 entries, 0 to 17913
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   REF_DATE       17914 non-null  int64
 1   GEO            17914 non-null  str
 2   DGUID          17914 non-null  str
 3   Sector         17914 non-null  str
 4   UOM            17914 non-null  str
 5   UOM_ID         17914 non-null  int64
 6   SCALAR_FACTOR  17914 non-null  str
 7   SCALAR_ID      17914 non-null  int64
 8   VECTOR         17914 non-null  str
 9   COORDINATE     17914 non-null  float64
 10  VALUE          14225 non-null  float64
 11  STATUS         3689 non-null   str
 12  SYMBOL         0 non-null      float64
 13  TERMINATED     0 non-null      float64
 14  DECIMALS       17914 non-null  int64
dtypes: float64(4), int64(4), str(7)
memory usage: 2.1 MB

In [6]:
df.head()

,REF_DATE,GEO,DGUID,Sector,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2013,Newfoundland and Labrador,2021A000210,Crop and animal production [BS11A00],Kilotonnes,198,units,0,v1013973304,2.3,114.0,NaN,NaN,NaN,0
1,2014,Newfoundland and Labrador,2021A000210,Crop and animal production [BS11A00],Kilotonnes,198,units,0,v1013973304,2.3,NaN,..,NaN,NaN,0
2,2015,Newfoundland and Labrador,2021A000210,Crop and animal production [BS11A00],Kilotonnes,198,units,0,v1013973304,2.3,NaN,..,NaN,NaN,0
3,2016,Newfoundland and Labrador,2021A000210,Crop and animal production [BS11A00],Kilotonnes,198,units,0,v1013973304,2.3,NaN,..,NaN,NaN,0
4,2017,Newfoundland and Labrador,2021A000210,Crop and animal production [BS11A00],Kilotonnes,198,units,0,v1013973304,2.3,NaN,..,NaN,NaN,0

In [2]:
#CHECK WHAT ALL THE COLUMNS TO DETERMINE USAGE
print(df.columns)
print("Shape of dataset:", df.shape)

Index(['REF_DATE', 'GEO', 'DGUID', 'Sector', 'UOM', 'UOM_ID', 'SCALAR_FACTOR',
       'SCALAR_ID', 'VECTOR', 'COORDINATE', 'VALUE', 'STATUS', 'SYMBOL',
       'TERMINATED', 'DECIMALS'],
      dtype='str')
Shape of dataset: (17914, 15)

In [5]:
df["Sector"].nunique()

133

In [7]:
#KEEP ONLY WHAT IS NEEDED
df = df[["REF_DATE", "GEO", "VALUE", "Sector"]]

In [8]:
print(df.columns)

Index(['REF_DATE', 'GEO', 'VALUE', 'Sector'], dtype='str')

In [9]:
#RENAME COLUMNS (MAKE IT CLEAN)
df.columns = ["Year", "Provinces", "Emissions", "Sectors"]

In [12]:
df.head()

,Year,Provinces,Emissions,Sectors
0,2013,Newfoundland and Labrador,114.0,Crop and animal production [BS11A00]
1,2014,Newfoundland and Labrador,NaN,Crop and animal production [BS11A00]
2,2015,Newfoundland and Labrador,NaN,Crop and animal production [BS11A00]
3,2016,Newfoundland and Labrador,NaN,Crop and animal production [BS11A00]
4,2017,Newfoundland and Labrador,NaN,Crop and animal production [BS11A00]

In [45]:
print(df.columns)

Index(['Year', 'Provinces', 'Emissions', 'Sectors'], dtype='object')

In [14]:
df.isna().sum()

Year            0
Provinces       0
Emissions    3689
Sectors         0
dtype: int64

In [14]:
#REMOVE NULLS
df = df.dropna()

In [17]:
#FIX DATA TYPES
df["Year"] = pd.to_datetime(df["Year"], format="%Y")
df["Emissions"] = df["Emissions"].astype(float)

In [19]:

latest_year = df["Year"].max()
df = df[df["Year"] >= latest_year - pd.DateOffset(years=10)]

In [20]:
#REMOVE TOTAL / DUPLICATES
df = df[df["Provinces"] != "Canada"]

In [21]:
#CREATE CLEAN DATASETS FOR PROVINCES (FOR MAIN CHARTS)

df_province = df.groupby(["Year", "Provinces"])["Emissions"].sum().reset_index()

df_province.to_csv("ghg_province_clean.csv", index=False)

In [22]:
# CREATE CLEAN DATASETS FOR SECTOR DATA (NS ONLY)
df_sector_ns = df[df["Provinces"] == "Nova Scotia"]

df_sector_ns = df_sector_ns.groupby(["Year", "Sectors"])["Emissions"].sum().reset_index()

df_sector_ns.to_csv("ghg_sector_ns_clean.csv", index=False)

In [27]:

from IPython.display import FileLink

FileLink("ghg_province_clean.csv")

C:\Users\USER-PC\ghg_province_clean.csv

In [32]:
print(df.columns)

Index(['Year', 'Provinces', 'Emissions', 'Sectors'], dtype='object')